apiVersion: v1
kind: Secret
metadata:
  name: controller-manager
  namespace: actions-runner-system
type: Opaque
stringData:
  github_app_id: "{{ .Values.githubApp.id }}"
  github_app_installation_id: "{{ .Values.githubApp.installationID }}"
  github_app_private_key: |
{{ .Values.githubApp.privateKey | indent 4 }}